#!/bin/sh
#
# Lists untracked `*.get` files and bundles that lack `*.get` files.
#
# Usage: ./list-untracked-bundles
#

git ls-files --others '*bundle/*.get'

git ls-files --others '*bundle/*/' | while read dir; do
  test -f ${dir%/}.get || echo "$dir"
done
