#!/bin/sh -e
#
# Deletes untracked `*.get` files and bundles lacking `*.get` files.
#
# Usage: .do/clean        # asks you for confirmation
# Usage: .do/clean -f     # no confirmation; force it
#
# Written in 2010 by Suraj N. Kurapati <https://github.com/sunaku>

test "$1" = '-f' && option='-t' || option='-p'
${0%/*}/orphans | xargs -r -n 1 $option rm -r
